apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: agent
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    resources:
      limits:
        memory: 512Mi
        cpu: 500m