# Static PersistentVolume for SonarQube data
# This PV uses hostPath and has no storageClassName to avoid dynamic provisioning
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarpv
  namespace: sonar
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/sonarqube

---
# Static PersistentVolumeClaim for SonarQube
# This PVC binds to the static PV 'sonarpv' and has no storageClassName
# Avoid creating dynamic PVCs with storageClass 'standard' in the sonar namespace to prevent duplicates
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarpvc
  namespace: sonar
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
