apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sonar
  name: sonarqube-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarqube-rolebinding
  namespace: sonar
subjects:
- kind: ServiceAccount
  name: sonarqube
  namespace: sonar
roleRef:
  kind: Role
  name: sonarqube-role
  apiGroup: rbac.authorization.k8s.io
