apiVersion: v1
kind: Secret
metadata:
  name: sonarqube
  namespace: sonar
type: Opaque
data:
  SONAR_JDBC_USERNAME: c29uYXJ1c2Vy  # base64 encoded 'sonaruser'
  SONAR_JDBC_PASSWORD: c29uYXJwYXNz  # base64 encoded 'sonarpass'
