apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: sonar
  labels:
    name: sonarqube
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 30085
      name: sonarport
  selector:
    name: sonarqube
