apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sql
  name: postgresql-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresql-rolebinding
  namespace: sql
subjects:
- kind: ServiceAccount
  name: postgresql
  namespace: sql
roleRef:
  kind: Role
  name: postgresql-role
  apiGroup: rbac.authorization.k8s.io
