apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
type: Opaque
data:
  jenkins-user: YWRtaW4=         # base64 for 'admin'
  jenkins-password: YWRtaW4xMjM= # base64 for 'admin123'

